server:
  port: ${PORT:0}
spring:
  profiles:
    active: local
  application:
    name: management-system-users
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: false
login:
  url: /auth/login
token:
  expiration-time: 3600000
  secret-key: ${TOKEN_SECRET_KEY}

authorization:
  token:
    header:
      name: Authorization
      prefix: "Bearer "
encrypt:
  key-store:
    location: classpath:management-system.p12
    password: ${KEYSTORE-PASSWORD}
    alias: management-system-key
    secret: ${KEYSTORE-SECRET-PASSWORD}
