server:
  port: ${PORT:0}
spring:
  profiles:
    active: local
  application:
    name: management-system-users
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
login:
  url: /auth/login
token:
  # 1 hour
  access-expiration: 3600000
  # 30 days
  refresh-expiration: 2592000000
  issuer: "Management system"
authorization:
  token:
    header:
      name: Authorization
      prefix: "Bearer "

# Public and Private keys will be load from the config server
#jwt:
#  private-key-location: file:../private.pem
#  public-key-location: file:../public.pem
