server:
  port: ${PORT:0}
spring:
  profiles:
    active: local
  application:
    name: management-system-image-creator
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  # File configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

