eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,gateway,refresh
security:
  allowed-origins: http://localhost:5000
logging:
  level:
    org:
      springframework:
        security: TRACE
        cloud:
          gateway: INFO
      web:
        reactive: DEBUG