server:
  port: 5000
spring:
  profiles:
    active: local
  application:
    name: management-system-api-gateway
  main:
    banner-mode: off
authorization:
  token:
    header:
      name: Authorization
      prefix: "Bearer "
# Load the public key from resources. This is provided from Config Server.
#jwt:
#  public-key-location: classpath:public.pem
