server:
  port: 5000
spring:
  profiles:
    active: local
  application:
    name: management-system-api-gateway
  main:
    banner-mode: off
authorization:
  token:
    header:
      name: Authorization
      prefix: "Bearer "
token:
  expiration-time: 3600000
  secret-key: ${TOKEN_SECRET_KEY}
