server:
  port: 5000
spring:
  profiles:
    active: local
  application:
    name: management-system-api-gateway
  main:
    banner-mode: off
  # Message broker required for busrefresh
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
authorization:
  token:
    header:
      name: Authorization
      prefix: "Bearer "
token:
  expiration-time: 3600000
  public-key-location: classpath:public.pem
