spring:
  cloud:
    config:
      server:
        vault:
          host: ${VAULT_HOST:127.0.0.1}
          port: 8200
          scheme: http
          backend: secret
          defaultKey: application
          profileSeparator: ","
          kvVersion: 2
          skipSslValidation: true
          timeout: 5
          authentication: TOKEN
          token: ${ROOT_TOKEN}
          order: 1
  #          namespace: null
