micronaut.application.name=management-system-desktop-client

#micronaut.environments=prod

#micronaut.server.port=-1

app.title=Management System
app.base-url=${BASE_URL:http://localhost:5000}

# Theme color variant: light, dark, system
# Property 'system' is not tested on all Linux desktops!
app.theme-variant=system
# Theme names: Flat, macOS, IntelliJ, Cyan-Purple, Material, Solarized-Carbon, Orange-Ocean
app.theme-name=Material

# Micronaut HTTP client
micronaut.http.client.read-timeout=30s
micronaut.http.client.connect-timeout=10s
micronaut.http.client.exception-on-error-status=true

# FlatLaf inspector (Ctrl + Alt + Shift + X to toggle it)
flat.inspector.enabled=true
# Enable app icon for Linux (default is false)
flat.linux-decorations.enabled=true

# Screen resolution
screen.preferred-resolution.width=1024
screen.preferred-resolution.height=768
screen.minimum-resolution.width=860
screen.minimum-resolution.height=680